### ISSUE TITLE
Babel code blocks render with a black line at the beginning

### ISSUE THREAD

**Issue by seandavi** [chaseadamsio/goorgeous#61] opened 2017-09-09 12:04 UTC
Code blocks such as:

```
#+BEGIN_SRC
ls
#+END_SRC
```

are rendered (under hugo) as:

```

ls
```

The same code block in Markdown renders without the blank line.

**Comment by cal2195** [comment] 2017-09-25 09:06
Any progress on this? :)

**Comment by chaseadamsio** [comment] 2017-09-26 13:15
goorgeous has been updated to the latest version in Hugo [here](https://github.com/gohugoio/hugo/commit/b8fabce217fcb52e3f273491bef95c7977058732#diff-bd290170e2912d3e8694db1a151066e5), which includes the fix for babel rendering. You can get the version as [v0.28 here](https://github.com/gohugoio/hugo/releases/tag/v0.28). Closing this issue as fixed, if you find that the rendering is still incorrect, feel free to reopen.

**Comment by wd** [comment] 2017-10-02 15:25
I've tested this use hugo v0.29，I think this issue have not fixed yet.

In org file:
```
#+BEGIN_SRC
line 1
line 2
line 3
#+END_SRC
```

The output html will be:
```
<pre><code>
line 1
line 2
line 3
</code></pre>
```

Which should be 

```
<pre><code>line 1
line 2
line 3</code></pre>
```
Otherwise, there will be a blank line at the first line.

**Comment by wd** [comment] 2017-10-04 06:50
Since it has been 2 days no one response this issue, and I didn't find a way to reopen this issue, I'm sorry but I have to mention you in this post, @chaseadamsio would you plz take look at this issue? Thanks.

**Comment by chaseadamsio** [comment] 2017-10-04 13:56
@wd This issue is fixed. The original issue was that there was a _blank_ new line in the code block. As you can see in the example I've included of rendering there is no difference in the way the HTML it outputs and the HTML you're suggesting it should output would render and the way you're suggesting deviates from the way every other element is generated. If you believe this is a problem and can reproduce the way the HTML is rendered in a browser as showing an extra new line, please feel free to open a new issue, but as far as I can tell @seandavi's issue is resolved.

![image](https://user-images.githubusercontent.com/1024544/31179545-1cf68e00-a8d1-11e7-9d1b-1861294ee3ab.png)

**Comment by chaseadamsio** [comment] 2017-10-04 13:58
I'll look into it this week. Please give me some time since this is one of a few _side projects_ that I maintain ontop of my normal job and being a dad. Aside from some contributions from @ageekymonk, I'm the only person maintaining this project and a few others & I'm getting to things the best I can.

**Comment by wd** [comment] 2017-10-05 03:41
@chaseadamsio  Sorry, I'm just trying to confirm you've received the notification. You did a great work for us, feel free to arrange your time to take a look to this issue. Thanks.

**Closed** 2017-11-26 22:58 UTC
Labels: bug
